// <auto-generated />
using CafeProject.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeProject.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410153831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CafeProject.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kahve",
                            Name = "Filtre Kahve",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Kahve",
                            Name = "Espresso",
                            Price = 45.0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Kahve",
                            Name = "Latte",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Şurup",
                            Name = "Karamel",
                            Price = 15.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Şurup",
                            Name = "Fıstık",
                            Price = 18.0
                        },
                        new
                        {
                            Id = 6,
                            Category = "Ekstra",
                            Name = "Süt",
                            Price = 10.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
